import { readFile, writeFile } from 'node:fs/promises';
import { demos, orderedDemos, card, scene, artwork, showcase } from './service-visuals.mjs';
let home=await readFile('index.html','utf8');
home=home.replace(/<!-- service-showcase:start -->[\s\S]*?<!-- service-showcase:end -->/, '<!-- service-showcase:start -->'+showcase()+'<!-- service-showcase:end -->').replace(/<!-- service-gallery:start -->[\s\S]*?<!-- service-gallery:end -->/, '<!-- service-gallery:start --><div class="projects">'+orderedDemos.map(card).join('')+'</div><!-- service-gallery:end -->');
await writeFile('index.html',home);
const head=home.slice(0,home.indexOf('<main id="main">'));
const footer=home.slice(home.indexOf('<footer'),home.indexOf('<dialog id="brief-dialog"'));
const dialogs=home.slice(home.indexOf('<dialog id="brief-dialog"'));
const art=demos.map(card);
const title=(label,line1,line2,description='',tone='')=>`<section class="page-hero ${tone}"><div class="eyebrow">WEBORA / ${label}</div><h1><span class="headline-line"><span>${line1}</span></span><span class="headline-line"><span class="serif">${line2}</span></span></h1><div class="page-hero-bottom"><p>${description}</p><span class="hero-index" aria-hidden="true">↘</span></div></section>`;
const cta=`<section class="end-cta section"><div class="eyebrow reveal">YOUR BRAND. ITS NEXT CHAPTER.</div><a href="./contact.html" class="reveal">Let’s make<br><em>something matter.</em><span>↗</span></a></section>`;
const band=(word,theme='orange')=>`<div class="word-band ${theme}" aria-hidden="true"><span data-drift>${word} ✳ ${word} ✳</span></div>`;
const serviceData=[
{slug:'web-design',name:'Web design & development',short:'Make the first<br>impression count.',tag:'A DISTINCTIVE DIGITAL HOME',desc:'A website should express your brand and make the next step obvious. I bring design and development together to create considered digital experiences.',offer:['Website strategy & page structure','Wireframes & visual direction','Responsive HTML, CSS & TypeScript development','Interaction, accessibility & launch checks'],outcome:'A clear, responsive website that helps visitors understand your offer and find their way to an enquiry.',process:['Define the audience, content, and main action.','Design the pages and refine the key journeys.','Build, test, and prepare a clear handover.'],color:'blue',symbol:'↗'},
{slug:'performance-marketing',name:'Social & performance marketing',short:'Get seen by<br>the right people.',tag:'CREATIVE WITH A DIRECTION',desc:'Connect your offer, audience, and message across organic social, Meta ads, and Google campaigns. Start with a goal; shape the creative around it.',offer:['Social content planning & campaign concepts','Facebook & Instagram ad creative','Google Ads campaign planning & setup','Agreed measurement & campaign reviews'],outcome:'A connected campaign plan with defined audiences, creative deliverables, and a clear basis for reviewing performance.',process:['Clarify the offer, audience, budget, and objective.','Prepare campaign structure, creative, and landing pages.','Launch with your approval and review against agreed goals.'],color:'lime',symbol:'◎'},
{slug:'ugc-content',name:'UGC & content creation',short:'More human.<br>More memorable.',tag:'STORIES MADE FOR THE FEED',desc:'Product stories, demonstrations, and short-form ideas that feel at home on social platforms. Content built around a real reason to care.',offer:['Content concepts, hooks & scripts','Product-led UGC briefs','Short-form video & reel creation','Platform-ready edits & agreed variants'],outcome:'A coherent set of content assets with a clear message, purposeful structure, and a format suited to where they will be seen.',process:['Explore the product, audience, and brand voice.','Agree concepts, usage, scope, and production needs.','Create, refine, and deliver the agreed edits.'],color:'peach',symbol:'▶'},
{slug:'influencer-marketing',name:'Influencer marketing',short:'The right voices.<br>A real connection.',tag:'PARTNERSHIPS WITH PURPOSE',desc:'Help your brand find creators whose audience and style make sense for the story you want to tell. A thoughtful fit matters more than a long list of names.',offer:['Creator research & shortlist','Campaign concept & creator brief','Deliverable and timeline coordination','Content review & campaign recap'],outcome:'A creator collaboration planned around audience fit, clear deliverables, and agreed content usage.',process:['Define the audience, campaign goals, and creator criteria.','Discuss creator fit, fees, rights, and deliverables.','Coordinate approved collaborations and review the content.'],color:'purple',symbol:'✳'},
{slug:'3d-map-design',name:'3D map & spatial design',short:'Give your place<br>a new perspective.',tag:'SPACES BECOME STORIES',desc:'Make a destination, development, or event easier to understand through custom map illustrations and spatial visuals.',offer:['Isometric map concepts','Location and landmark illustration','Presentation-ready spatial graphics','Web and social export formats'],outcome:'A distinctive visual map that communicates the places and details your audience needs to notice. These are illustrative assets, not survey-grade maps.',process:['Gather the location references and essential landmarks.','Develop the perspective, hierarchy, and visual style.','Refine the details and export the agreed formats.'],color:'purple',symbol:'⌖'}
];
serviceData.push(
{slug:'shopify',name:'Shopify design & development',short:'Your brand.<br>Ready for commerce.',tag:'A BETTER STOREFRONT EXPERIENCE',desc:'Bring your brand into a considered Shopify store. I connect visual design, theme development, and clear product journeys so the shopping experience feels coherent.',offer:['Shopify storefront and product-page design','Theme customisation and development','Collection, navigation, and cart experience','Store setup support and launch checks'],outcome:'A Shopify storefront shaped around your products, brand, and agreed shopping journeys. Platform subscriptions, paid themes, and app fees are agreed separately.',process:['Map the products, customers, and store requirements.','Design the storefront and customise the agreed theme.','Check key journeys and prepare the store for handover.'],color:'sage',symbol:'↗'},
{slug:'mobile-apps',name:'Mobile app development',short:'An idea.<br>A daily companion.',tag:'MOBILE EXPERIENCES THAT MAKE SENSE',desc:'From app flows to React Native development, I shape mobile experiences around the tasks your users need to complete.',offer:['App flow and interface design','React Native mobile development','API and backend integration','Testing and release preparation within agreed scope'],outcome:'A mobile application built around agreed screens and functionality. Platform requirements, developer accounts, and store submission responsibilities are defined in the project scope.',process:['Define the core user journeys and platform needs.','Design and develop the agreed app experience.','Test key flows and prepare the delivery or release.'],color:'blue',symbol:'▣'}
);
serviceData[0].offer=['Website strategy, wireframes & visual design','HTML, CSS, JavaScript, TypeScript & React interfaces','Node.js or PHP backend development','SQL or MongoDB data integration'];
serviceData[0].desc='Brand-led websites and web applications, from the first wireframe to the frontend and backend. The technology is selected around the experience and functionality your business needs.';
const articleData=[
{slug:'website-brief',tag:'WEBSITE STRATEGY',title:'Before the pixels: a better website brief.',intro:'The most useful website brief does not start with colours. It starts with the change you want the website to make.',sections:[['Choose one primary action','Should a visitor book a call, enquire about a service, or explore a product? Decide which action matters most. Secondary journeys can still exist, but the main path needs a clear priority.'],['Describe the visitor’s questions','Write down what someone needs to know before contacting you: what you do, who it is for, what the process looks like, and what makes your approach relevant. This is the beginning of your page structure.'],['Collect proof, not decoration','Gather real project images, clear descriptions of your role, and results you can substantiate. If you are starting out, label concept work honestly and explain the thinking behind it.'],['Agree the practical boundaries','List the pages, required features, content responsibilities, budget range, and target timeline. A shared understanding now gives design and development a much clearer direction.']]},
{slug:'content-with-purpose',tag:'CONTENT & CREATIVE',title:'Give every piece of content a job.',intro:'A beautiful feed is useful when it also helps people understand your brand. Give each content idea a purpose before deciding on the format.',sections:[['Introduce, explain, or invite','Some posts introduce the brand. Others explain a product or answer a question. Others invite the viewer to take a next step. Choose one main job for each idea so the message stays focused.'],['Start with the product truth','What is useful, surprising, or distinctive about the product? Build the story around a detail you can actually show. A clear demonstration often communicates more than a list of broad claims.'],['Let the format follow the idea','A quick demonstration might work as a short video; a process might need a sequence of images. Choose the format that makes the idea easiest to understand, then adapt it for the platform.'],['Review what the content taught you','Compare the response with the original purpose. Questions, saves, relevant enquiries, and viewing patterns can each tell a different story. Use that information to decide what to make next.']]},
{slug:'connected-brand',tag:'BRAND THINKING',title:'One brand, every touchpoint.',intro:'Your website, social content, advertising, and creator collaborations should feel like parts of the same conversation.',sections:[['Keep the promise consistent','Someone arriving from an advert should recognise the same offer and tone on the landing page. Make the connection visible in the headline, imagery, and next action.'],['Build a small, usable visual language','A clear type hierarchy, a considered colour palette, and a few repeatable composition rules can keep different formats connected without making them identical.'],['Give creators a direction, not a disguise','A creator brief should explain the product, audience, factual claims, and usage requirements. Leave room for the creator’s natural voice within those boundaries.'],['Make the handover part of the work','Keep final assets, editable files where agreed, and simple usage notes organised. A brand system is more useful when the person running the next campaign can apply it.']]}
];
const cards=()=>serviceData.map((s,i)=>`<a class="service-card reveal ${s.color}" href="./service-${s.slug}.html"><div class="eyebrow">0${i+1} / ${s.tag}</div><div class="service-card-middle"><h2>${s.short}</h2>${scene(demos.find(d=>d.slug===s.slug))}</div><div class="service-card-bottom"><h3>${s.name}</h3><span>Explore service ↗</span></div></a>`).join('');
const articles=()=>articleData.map((a,i)=>`<a class="insight-card reveal" href="./insight-${a.slug}.html"><div class="insight-art art-${i}"><span aria-hidden="true">${['Aa','↗','✳'][i]}</span><small>FIELD NOTES / 0${i+1}</small></div><div class="eyebrow">${a.tag} / WEBORA NOTES</div><h3>${a.title}</h3><span class="read-link">Read the note ↗</span></a>`).join('');
const pages={};
pages['work']={name:'Work',desc:'Explore Webora’s self-initiated concepts in websites, content and 3D map design.',body:title('WORK','Ideas made','visible.','A closer look at creative possibilities for brands. These self-initiated studies are concepts, not commissioned client projects.')+`<section class="section work-index"><div class="filter-bar" role="group" aria-label="Filter projects"><button data-filter="all" aria-pressed="true">All explorations <span>03</span></button><button data-filter="web" aria-pressed="false">Websites</button><button data-filter="content" aria-pressed="false">Content & campaigns</button><button data-filter="spatial" aria-pressed="false">3D & spatial</button></div><p class="filter-status" role="status">Showing 3 concept projects</p><div class="projects">${art.join('')}</div></section>`+cta};
pages['services']={name:'Services',desc:'Web design, development, paid media, UGC, influencer marketing and 3D maps for brands.',body:title('SERVICES','Everything connects.','Make it count.','From the website people discover to the content they remember. Choose one service or build a connected project around your brand.')+`<section class="section service-stack">${cards()}</section><section class="section scope-note reveal"><div class="eyebrow">BUILT AROUND YOUR BRIEF</div><h2>The right scope.<br><em class="serif">Before we start.</em></h2><p>Each project begins with a conversation about the goal, deliverables, timing, and budget. Media spend, creator fees, production needs, and ongoing support are discussed separately where relevant.</p></section>`+cta};
pages['technology']={name:'Technology',desc:'Thoughtful frontend development with HTML, CSS, TypeScript and JavaScript.',body:title('TECHNOLOGY','Beautiful outside.','Considered inside.','The code is part of the experience. I build websites around clear structure, responsive layouts, and purposeful interaction.')+`<section class="tech-stage"><div class="tech-orbit" aria-hidden="true"><span>HTML</span><span>CSS</span><span>TS</span><span>JS</span><b>webora✳</b></div><div class="tech-caption">THE FOUNDATION FOR YOUR NEXT DIGITAL EXPERIENCE</div></section><section class="section"><div class="section-heading reveal"><div class="eyebrow">HOW I BUILD</div><h2>Every detail has<br><em class="serif">a reason.</em></h2></div><div class="principle-grid">${[['01','Structure first','Semantic HTML gives content a clear hierarchy, from the page title to the next action.'],['02','Every screen matters','Flexible layouts adapt to mobile, tablet, and desktop instead of shrinking a desktop composition.'],['03','Motion with purpose','Entrance sequences, scroll reveals, and hover feedback support the story. Reduced-motion preferences are respected.'],['04','A clear handover','Readable source files and practical setup notes make it easier to maintain and extend the website.']].map(([n,t,p])=>`<article class="reveal"><span>${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section><section class="section tech-panel"><div><div class="eyebrow">A LIGHTWEIGHT FOUNDATION</div><h2>Less friction.<br><em class="serif">More possibility.</em></h2></div><div><p>HTML and CSS shape the experience. TypeScript and JavaScript bring the interactions to life. Integrations and hosting are chosen to suit the project’s actual needs.</p><ul class="deliverables"><li>Responsive frontend development</li><li>Interaction and animation design</li><li>Enquiry and social platform connections</li><li>Static hosting preparation</li></ul></div></section>`+cta};
pages['about']={name:'About',desc:'Webora is an independent creative practice connecting design, development and marketing.',body:title('ABOUT WEBORA','Independent mind.','Connected thinking.','A freelance creative practice for brands that want their website, content, and marketing to work together.')+band('A LITTLE DIFFERENT.')+`<section class="section intro"><div class="eyebrow reveal">THE WAY I SEE IT</div><div><h2 class="reveal">A brand is more<br>than a <em class="serif">single moment.</em></h2><div class="intro-copy reveal"><p>It is the first page someone visits. The story they stop scrolling for. The campaign that gives them a reason to look again.</p><p>Webora brings those moments into one creative direction. I work across websites, Shopify stores, React Native apps, full-stack development, social marketing, content, creator partnerships, and 3D maps.</p></div></div></section><section class="section about-values"><div class="eyebrow reveal">WHAT WORKING TOGETHER FEELS LIKE</div><div class="value-row reveal"><span>01</span><h3>A direct conversation.</h3><p>Talk with the person shaping the work. Share context, ask questions, and take part in the decisions that matter.</p></div><div class="value-row reveal"><span>02</span><h3>A connected perspective.</h3><p>Consider how the website, the campaign, and the content fit together, even when the project starts with just one of them.</p></div><div class="value-row reveal"><span>03</span><h3>Care in the details.</h3><p>Typography, interaction, the right phrase, the right crop. Small decisions add up to how a brand feels.</p></div></section>`+cta};
pages['insights']={name:'Insights',desc:'Practical Webora notes on website briefs, content and connected brand experiences.',body:title('INSIGHTS','A few thoughts.','A fresh perspective.','Practical notes from Webora on design, content, and bringing a brand together. Useful starting points for your next project.')+`<section class="section insight-grid">${articles()}</section>`+cta};
pages['careers']={name:'Careers & collaboration',desc:'Connect with Webora about creative collaboration. No salaried job vacancies are currently listed.',body:title('CAREERS & COLLABORATION','Good people.','Good possibilities.','Webora is an independent freelance practice. This is a place to introduce your work and explore potential project collaborations.')+`<section class="section collaboration-panel"><div class="eyebrow">CREATIVE CONNECTIONS</div><h2 class="reveal">Different strengths.<br><em class="serif">Shared standards.</em></h2><p class="reveal">If your work complements design, development, content, or spatial storytelling, you can share your portfolio. Any collaboration depends on project fit and an agreed scope.</p><div class="collab-tags reveal"><span>Designers</span><span>Developers</span><span>Content creators</span><span>3D artists</span></div><div class="vacancy-note reveal"><h3>Current opportunities</h3><p>No salaried job vacancies are listed here. Portfolio introductions are welcome; this is not a promise of employment or paid work.</p><a href="https://wa.me/918469030829?text=Hi%20Webora%2C%20I%27d%20like%20to%20introduce%20my%20work%20for%20a%20potential%20collaboration." class="pill" target="_blank" rel="noopener noreferrer">Introduce your work ↗</a></div></section>`};
pages['contact']={name:'Contact',desc:'Start your Webora project on WhatsApp. Web design, content, marketing and 3D design enquiries.',body:title('CONTACT','Big idea?','Let’s hear it.','A new website, a campaign, a creative challenge. Tell me where you want to go and we can work out the next step.','contact-hero')+`<section class="section contact-page"><div class="contact-details reveal"><div class="eyebrow">START THE CONVERSATION</div><h2>It starts<br>with <em class="serif">hello.</em></h2><a href="https://wa.me/918469030829" target="_blank" rel="noopener noreferrer">+91 84690 30829 ↗</a><a href="https://www.instagram.com/webora.co.in_/" target="_blank" rel="noopener noreferrer">Instagram / @webora.co.in_ ↗</a><p>Prefer a quick message? Use the direct WhatsApp link. For a little more context, fill in the project brief.</p></div><div class="contact-form-panel reveal"><h3>What are you thinking?</h3><p>Share the basics. You’ll review the message in WhatsApp before sending.</p><button class="pill dark" id="brief-open">Write your project brief ↗</button><div class="contact-prompts"><span>01 / Your brand or business</span><span>02 / The service you need</span><span>03 / Your goals and timing</span></div></div></section><section class="section faq"><div class="eyebrow reveal">A FEW USEFUL ANSWERS</div><h2 class="reveal">Before we <em class="serif">begin.</em></h2><details><summary>How much does a project cost?<b>+</b></summary><div><p>Pricing depends on the agreed scope, deliverables, complexity, and timeline. Share the brief first so the estimate can reflect what you actually need.</p></div></details><details><summary>Can I book more than one service?<b>+</b></summary><div><p>Yes. A website, campaign, and content can be planned together, with the responsibilities and deliverables agreed before work begins.</p></div></details><details><summary>What should I prepare?<b>+</b></summary><div><p>Your business overview, project goals, any existing brand assets, useful references, and a target timeline are a good starting point.</p></div></details></section>`};
serviceData.forEach((s,i)=>{pages['service-'+s.slug]={name:s.name,desc:s.desc,body:title('SERVICES / 0'+(i+1),s.short.split('<br>')[0],s.short.split('<br>')[1],s.desc)+`<section class="service-feature service-feature-illustrated ${s.color}">${artwork(demos.find(d=>d.slug===s.slug))}</section><section class="section detail-split"><div class="reveal"><div class="eyebrow">WHAT WE CAN CREATE</div><h2>A clear scope.<br><em class="serif">A useful outcome.</em></h2></div><div class="reveal"><p>${s.outcome}</p><ul class="deliverables">${s.offer.map(x=>`<li>${x}</li>`).join('')}</ul><a class="pill" href="./contact.html?service=${encodeURIComponent(s.name)}">Discuss your project ↗</a></div></section><section class="section service-process"><div class="eyebrow reveal">FROM IDEA TO DELIVERY</div><div class="steps">${s.process.map((p,n)=>`<article class="reveal"><span>0${n+1}</span><h3>${['Define the direction.','Shape the work.','Bring it to life.'][n]}</h3><p>${p}</p></article>`).join('')}</div></section>`+cta};});
const projectSlugs=['forma','day-off','new-perspectives','sunday-supply','pace'];
projectSlugs.forEach((slug,i)=>{const d=demos[i];const next=demos[(i+1)%5];pages['work-'+slug]={name:d.name+' — service in focus',desc:d.detail,body:title('SERVICE IN FOCUS / 0'+(i+1),d.name.split(' & ')[0],d.name.includes(' & ')?'& '+d.name.split(' & ')[1]:d.strap,d.detail)+`<section class="case-visual case-service">${artwork(d)}</section><section class="section detail-split"><div class="reveal"><div class="eyebrow">WHAT THIS COULD MEAN FOR YOUR BRAND</div><h2>${d.strap}</h2></div><div class="reveal"><p>${d.detail}</p><h3>Built around your brief</h3><p>We start with your audience, brand, and goals. Then agree the scope, content, and deliverables before shaping the work together.</p><p class="concept-note">This animated service illustration explains the kind of work available. It is not a commissioned client project, live product, or campaign result.</p><a class="pill" href="./service-${d.slug}.html">Explore the service ↗</a></div></section><a class="next-project" href="./${next.route}.html"><span>NEXT SERVICE IN FOCUS</span><h2>${next.name} ↗</h2></a>`+cta};});
articleData.forEach(a=>{pages['insight-'+a.slug]={name:a.title,desc:a.intro,body:`<section class="section article-hero"><a class="eyebrow" href="./insights.html">← ALL INSIGHTS / ${a.tag}</a><h1>${a.title}</h1><p>${a.intro}</p><span class="article-byline">WEBORA FIELD NOTES · 3 MIN READ</span></section><article class="article-body">${a.sections.map(([t,p],i)=>`<section class="reveal"><span>0${i+1}</span><h2>${t}</h2><p>${p}</p></section>`).join('')}<a class="pill" href="./contact.html">Put the idea into practice ↗</a></article>`+cta};});
pages.privacy={name:'Privacy',desc:'How this Webora website handles enquiry information and external links.',body:title('PRIVACY','Clear by','design.','A short explanation of how this website works.')+`<article class="article-body"><section><h2>Your project brief</h2><p>The enquiry form prepares a WhatsApp link containing the details you enter. When you continue, those details are passed to WhatsApp so you can review and send the message. This website does not save your form details to a server.</p></section><section><h2>External services</h2><p>WhatsApp and Instagram links take you to services with their own privacy policies. Fonts are requested from Google Fonts; that request exposes standard connection information, such as your IP address, to the font provider.</p></section><section><h2>Cookies and preferences</h2><p>No analytics or advertising tracking is included in this website’s source. The motion toggle saves your preference in this browser using local storage. A hosting provider may process standard access logs.</p></section><section><h2>Questions</h2><p>Contact Webora on <a href="https://wa.me/918469030829">WhatsApp at +91 84690 30829</a> for questions about an enquiry or the information you have shared.</p></section></article>`};
await (await import('./brand-pages.mjs')).enhance({pages,title,cta,art,band});
for(const [slug,page] of Object.entries(pages)){
 let pageHead=head.replace(/<title>[\s\S]*?<\/title>/,`<title>${page.name} — Webora</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${page.desc.replaceAll('"','&quot;')}">`);
 const navSlug=slug.startsWith('service-')?'services':slug.startsWith('work-')?'work':slug.startsWith('insight-')?'insights':slug;
 pageHead=pageHead.replace(`href="./${navSlug}.html"`,`href="./${navSlug}.html" aria-current="page"`);
 await writeFile(slug+'.html',pageHead+`<main id="main">${page.body}</main>`+footer+dialogs);
}
console.log(`Generated ${Object.keys(pages).length} additional Webora pages.`);
